name: pmsc_auth
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.1.0
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.3 
  google_fonts: ^2.1.0
  fluttertoast: ^8.0.8
  local_auth: ^1.1.8
  dio: ^4.0.0
  http: ^0.13.3
  localstorage: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.1.4

flutter:

  uses-material-design: true

  assets:
    - assets/